Use `if <cond> {} else { <then> }` instead of `if !<cond> { <then> }`
This approach works on *every* edition and emits the desired output consistently:

```
error[E0308]: mismatched types
  --> $DIR/issue-28308.rs:6:13
   |
LL |     assert!("foo");
   |             ^^^^^ expected `bool`, found `&str`
```